---
deployment:
  tasks:
    # Set deployment path (your Laravel root)
    - export DEPLOYPATH=/home/nohfilco/epicerie-le-continent.designatrix.com

    # Pull the latest files (cPanel does this automatically but this ensures sync)
    - /bin/git pull

    # Install Composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist -d $DEPLOYPATH

    # Laravel permissions (important on shared hosting)
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache

    # Laravel optimization
    - php $DEPLOYPATH/artisan migrate --force || true
    - php $DEPLOYPATH/artisan optimize
