---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nohfilco/christelle-store.designatrix.com
    - cd $DEPLOYPATH

    # Install composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist -d $DEPLOYPATH

    # Set correct permissions
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache

    # Run Laravel optimizations
    - /usr/local/bin/php $DEPLOYPATH/artisan optimize
