---
deployment:
  tasks:
    # Set deploy path
    - export DEPLOYPATH=/home/nohfilco/epicerie-le-continent.designatrix.com

    # Ensure we are in the correct repo directory
    - cd $DEPLOYPATH

    # Fetch the latest changes
    - /usr/local/cpanel/3rdparty/bin/git fetch origin

    # Reset to match remote main branch
    - /usr/local/cpanel/3rdparty/bin/git reset --hard origin/main || true

    # Pull the latest changes safely
    - /usr/local/cpanel/3rdparty/bin/git pull origin main

    # Install composer dependencies
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist -d $DEPLOYPATH

    # Set correct permissions
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache

    # Run Laravel optimizations
    - /usr/local/bin/php $DEPLOYPATH/artisan optimize
